# Generated by Django 5.0.7 on 2024-08-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='participants',
            new_name='members',
        ),
    ]
