# Generated by Django 5.0.7 on 2024-08-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
